using RedHerring.Fingerprint;
using GuiKey = ImGuiNET.ImGuiKey;

namespace RedHerring.ImGui;

internal static class Convert
{
    public static GuiKey ToImGuiKey(Key key)
    {
        return key switch
        {
            Key.Unknown => GuiKey.None,
            Key.ShiftLeft => GuiKey.LeftShift,
            Key.ShiftRight => GuiKey.RightShift,
            Key.ControlLeft => GuiKey.LeftCtrl,
            Key.ControlRight => GuiKey.RightCtrl,
            Key.AltLeft => GuiKey.LeftAlt,
            Key.AltRight => GuiKey.RightAlt,
            Key.SuperLeft => GuiKey.LeftSuper,
            Key.SuperRight => GuiKey.RightSuper,
            Key.Menu => GuiKey.Menu,
            Key.F1 => GuiKey.F1,
            Key.F2 => GuiKey.F2,
            Key.F3 => GuiKey.F3,
            Key.F4 => GuiKey.F4,
            Key.F5 => GuiKey.F5,
            Key.F6 => GuiKey.F6,
            Key.F7 => GuiKey.F7,
            Key.F8 => GuiKey.F8,
            Key.F9 => GuiKey.F9,
            Key.F10 => GuiKey.F10,
            Key.F11 => GuiKey.F11,
            Key.F12 => GuiKey.F12,
            Key.Up => GuiKey.UpArrow,
            Key.Down => GuiKey.DownArrow,
            Key.Left => GuiKey.LeftArrow,
            Key.Right => GuiKey.RightArrow,
            Key.Enter => GuiKey.Enter,
            Key.Escape => GuiKey.Escape,
            Key.Space => GuiKey.Space,
            Key.Tab => GuiKey.Tab,
            Key.Backspace => GuiKey.Backspace,
            Key.Insert => GuiKey.Insert,
            Key.Delete => GuiKey.Delete,
            Key.PageUp => GuiKey.PageUp,
            Key.PageDown => GuiKey.PageDown,
            Key.Home => GuiKey.Home,
            Key.End => GuiKey.End,
            Key.CapsLock => GuiKey.CapsLock,
            Key.ScrollLock => GuiKey.ScrollLock,
            Key.PrintScreen => GuiKey.PrintScreen,
            Key.Pause => GuiKey.Pause,
            Key.NumLock => GuiKey.NumLock,
            Key.Keypad0 => GuiKey.Keypad0,
            Key.Keypad1 => GuiKey.Keypad1,
            Key.Keypad2 => GuiKey.Keypad2,
            Key.Keypad3 => GuiKey.Keypad3,
            Key.Keypad4 => GuiKey.Keypad4,
            Key.Keypad5 => GuiKey.Keypad5,
            Key.Keypad6 => GuiKey.Keypad6,
            Key.Keypad7 => GuiKey.Keypad7,
            Key.Keypad8 => GuiKey.Keypad8,
            Key.Keypad9 => GuiKey.Keypad9,
            Key.KeypadDivide => GuiKey.KeypadDivide,
            Key.KeypadMultiply => GuiKey.KeypadMultiply,
            Key.KeypadSubtract => GuiKey.KeypadSubtract,
            Key.KeypadAdd => GuiKey.KeypadAdd,
            Key.KeypadDecimal => GuiKey.KeypadDecimal,
            Key.KeypadEnter => GuiKey.KeypadEnter,
            Key.A => GuiKey.A,
            Key.B => GuiKey.B,
            Key.C => GuiKey.C,
            Key.D => GuiKey.D,
            Key.E => GuiKey.E,
            Key.F => GuiKey.F,
            Key.G => GuiKey.G,
            Key.H => GuiKey.H,
            Key.I => GuiKey.I,
            Key.J => GuiKey.J,
            Key.K => GuiKey.K,
            Key.L => GuiKey.L,
            Key.M => GuiKey.M,
            Key.N => GuiKey.N,
            Key.O => GuiKey.O,
            Key.P => GuiKey.P,
            Key.Q => GuiKey.Q,
            Key.R => GuiKey.R,
            Key.S => GuiKey.S,
            Key.T => GuiKey.T,
            Key.U => GuiKey.U,
            Key.V => GuiKey.V,
            Key.W => GuiKey.W,
            Key.X => GuiKey.X,
            Key.Y => GuiKey.Y,
            Key.Z => GuiKey.Z,
            Key.Number0 => GuiKey._0,
            Key.Number1 => GuiKey._1,
            Key.Number2 => GuiKey._2,
            Key.Number3 => GuiKey._3,
            Key.Number4 => GuiKey._4,
            Key.Number5 => GuiKey._5,
            Key.Number6 => GuiKey._6,
            Key.Number7 => GuiKey._7,
            Key.Number8 => GuiKey._8,
            Key.Number9 => GuiKey._9,
            Key.GraveAccent => GuiKey.GraveAccent,
            Key.Minus => GuiKey.Minus,
            Key.Equal => GuiKey.KeypadAdd,
            Key.LeftBracket => GuiKey.LeftBracket,
            Key.RightBracket => GuiKey.RightBracket,
            Key.Semicolon => GuiKey.Semicolon,
            Key.Apostrophe => GuiKey.Apostrophe,
            Key.Comma => GuiKey.Comma,
            Key.Period => GuiKey.Period,
            Key.Slash => GuiKey.Slash,
            Key.BackSlash => GuiKey.Backslash,
            _ => GuiKey.None,
        };
    }

    public static GuiKey ToImGuiKey(GamepadButton button)
    {
        return button switch
        {
            GamepadButton.Unknown => GuiKey.None,
            GamepadButton.A => GuiKey.GamepadFaceDown,
            GamepadButton.B => GuiKey.GamepadFaceRight,
            GamepadButton.X => GuiKey.GamepadFaceLeft,
            GamepadButton.Y => GuiKey.GamepadFaceUp,
            GamepadButton.LeftBumper => GuiKey.GamepadL3,
            GamepadButton.RightBumper => GuiKey.GamepadR3,
            GamepadButton.Back => GuiKey.GamepadBack,
            GamepadButton.Start => GuiKey.GamepadStart,
            GamepadButton.Home => GuiKey.None,
            GamepadButton.LeftStick => GuiKey.GamepadL1, // ??
            GamepadButton.RightStick => GuiKey.GamepadR1, // ??
            GamepadButton.DPadUp => GuiKey.GamepadDpadUp,
            GamepadButton.DPadRight => GuiKey.GamepadDpadRight,
            GamepadButton.DPadDown => GuiKey.GamepadDpadDown,
            GamepadButton.DPadLeft => GuiKey.GamepadDpadLeft,
            _ => GuiKey.None,
        };
    }
}